version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - portainer_data:/data:rw

  dashboard-qqq:
    build:
      context: .
      dockerfile: Dockerfile_qqq.react
    container_name: dashboard-qqq
    restart: always
    ports:
      - "3000:3000"
 
 

volumes:
  portainer_data:
